services:
  - type: web
    name: newcos-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      # Data.gov.in
      - key: DGI_API_KEY
        sync: false
      - key: DGI_RESOURCE_ID
        sync: false
      - key: PAGE_LIMIT
        value: "1000"
      - key: MAX_PAGES
        value: "200"
 
      # Gmail SMTP (App Password)
      - key: BREVO_HOST
        value: "smtp-relay.gmail.com"
      - key: BREVO_PORT
        value: "465"
      - key: BREVO_USER
        sync: false
      - key: BREVO_PASS
        sync: false
      - key: MAIL_FROM
        value: "vijaychettinese@gmail.com"
      - key: MAIL_TO
        sync: false
      - key: MAIL_SUBJECT
        value: "Newly Registered Companies"
 
      - key: CRON_SECRET
        sync: false
 
    healthCheckPath: /healthz